services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${NZBGETPUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=002 # Folder 775 (drwxrwxr-x) Files 664 (-rw-rw-r--)
    volumes:
      - ${CFG}/config/nzbget:/config # config files
      - ${DL}:/downloads # download folder

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${SONARRPUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=002 # Folder 775 (drwxrwxr-x) Files 664 (-rw-rw-r--)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CFG}/config/sonarr:/config # config files
      - ${DATA}:/data

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${RADARRPUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=002 # Folder 775 (drwxrwxr-x) Files 664 (-rw-rw-r--)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CFG}/config/radarr:/config # config files
      - ${DATA}:/data

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${BAZARRPUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=002 # Folder 775 (drwxrwxr-x) Files 664 (-rw-rw-r--)
    volumes:
      - ${CFG}/config/bazarr:/config # config files
      - ${DATA}:/data
