services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${NZBGETPUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=002 # Folder 775 (drwxrwxr-x) Files 664 (-rw-rw-r--)
    volumes:
      - /mnt/storage/media-dl/config/nzbget:/config # config files
      - /mnt/storage/downloads:/data/downloads # download folder

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${SONARRPUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=002 # Folder 775 (drwxrwxr-x) Files 664 (-rw-rw-r--)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/media-dl/config/sonarr:/config # config files
      - /mnt/storage:/data

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${RADARRPUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=002 # Folder 775 (drwxrwxr-x) Files 664 (-rw-rw-r--)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/media-dl/config/radarr:/config # config files
      - /mnt/storage:/data

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${BAZARRPUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=002 # Folder 775 (drwxrwxr-x) Files 664 (-rw-rw-r--)
    volumes:
      - /mnt/storage/media-dl/config/bazarr:/config # config files
      - /mnt/storage:/data

  overseerr:
      image: sctx/overseerr:latest
      container_name: overseerr
      environment:
        - LOG_LEVEL=debug
        - TZ=${TZ} # timezone, defined in .env
        - PORT=5055 #optional
      ports:
        - 5055:5055
      volumes:
        - /mnt/storage/media-dl/config/overseerr:/app/config
      restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PLEXPUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/storage/media-dl/config/plex:/config
      - /mnt/storage/media/tv:/tv
      - /mnt/storage/media/movies:/movies
    restart: unless-stopped
